//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template_4335.Windows.MuhametzanovaAR
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExcelEntities : DbContext
    {
        public ExcelEntities()
            : base("name=ExcelEntities")
        {
        }

        private static ExcelEntities _context = new ExcelEntities();

        public static ExcelEntities GetContext()
        {
            if (_context == null)
                _context = new ExcelEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Uslugi> Uslugi { get; set; }
    }
}
