//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template_4335.Windows.MuhametzanovaAR
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;

    public partial class Uslugi
    {
        [JsonPropertyName("Id")]
        public string Id { get; set; }

        [JsonPropertyName("CodeOrder")]
        public string IdZakaza { get; set; }

        [JsonPropertyName("CreateDate")]
        public string DataSozdaniya { get; set; }

        [JsonPropertyName("CreateTime")]
        public string VremyaZakaza { get; set; }

        [JsonPropertyName("CodeClient")]
        public string IdClienta { get; set; }

        [JsonPropertyName("Services")]
        public string Uslugii { get; set; }

        [JsonPropertyName("Status")]
        public string Statuss { get; set; }

        [JsonPropertyName("ClosedDate")]
        public string DataZakritiya { get; set; }

        [JsonPropertyName("ProkatTime")]
        public Nullable<int> VremyaProkata { get; set; }
    }
}
